/*
Package apimaticcalculator

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package tests

import (
    "apimaticcalculator"
    "apimaticcalculator/controllers"
    "github.com/apimatic/go-core-runtime/https"
)

var SimpleCalculatorController controllers.SimpleCalculatorController

func init() {
    config := apimaticcalculator.ConfigurationFactory(
        apimaticcalculator.WithHttpConfiguration(
            apimaticcalculator.HttpConfigurationFactory(
                https.WithTimeout(30),
            ),
        ),
    )
    
    client := apimaticcalculator.NewClient(config)
    
    SimpleCalculatorController = client.SimpleCalculatorController
}
