/*
Package apimaticcalculator

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

// Possible operators are sum, subtract, multiply, divide
type OperationTypeEnum string

const (
    OperationTypeEnum_SUM      OperationTypeEnum = "SUM"
    OperationTypeEnum_SUBTRACT OperationTypeEnum = "SUBTRACT"
    OperationTypeEnum_MULTIPLY OperationTypeEnum = "MULTIPLY"
    OperationTypeEnum_DIVIDE   OperationTypeEnum = "DIVIDE"
)
